// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32kZrQJM2GRhEUJAqgWORl10rFHZcWak',
    appId: '1:784564044680:web:7f67d9f02cd0e0a2eb303d',
    messagingSenderId: '784564044680',
    projectId: 'hr-app-a2e91',
    authDomain: 'hr-app-a2e91.firebaseapp.com',
    storageBucket: 'hr-app-a2e91.appspot.com',
    measurementId: 'G-XNTNXZFWZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0k24RX5Gi9jUiLBXe-RXc4e59qYWDpuQ',
    appId: '1:784564044680:android:1374690545b91a0ceb303d',
    messagingSenderId: '784564044680',
    projectId: 'hr-app-a2e91',
    storageBucket: 'hr-app-a2e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAItBd2i8nRcqcylCzdHMeY27dcBRrj7QU',
    appId: '1:784564044680:ios:4b99ef570283b79beb303d',
    messagingSenderId: '784564044680',
    projectId: 'hr-app-a2e91',
    storageBucket: 'hr-app-a2e91.appspot.com',
    iosClientId: '784564044680-cgf5p0dsrgc9unfc90ck32g7dm5e32s8.apps.googleusercontent.com',
    iosBundleId: 'com.seafresh.sfiHr',
  );
}
